// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class Achievement
{
    public const string achievement = "CgkI9Iy775wLEAIQAQ"; // <GPGSID>
    public const string achievement_2 = "CgkI9Iy775wLEAIQAg"; // <GPGSID>
    public const string achievement_3 = "CgkI9Iy775wLEAIQAw"; // <GPGSID>
    public const string achievement_4 = "CgkI9Iy775wLEAIQMg"; // <GPGSID>
    public const string achievement_5 = "CgkI9Iy775wLEAIQBA"; // <GPGSID>
    public const string achievement_6 = "CgkI9Iy775wLEAIQBQ"; // <GPGSID>
    public const string achievement_7 = "CgkI9Iy775wLEAIQBg"; // <GPGSID>
    public const string achievement_8 = "CgkI9Iy775wLEAIQBw"; // <GPGSID>
    public const string achievement_9 = "CgkI9Iy775wLEAIQCA"; // <GPGSID>
    public const string achievement_10 = "CgkI9Iy775wLEAIQCQ"; // <GPGSID>
    public const string achievement_11 = "CgkI9Iy775wLEAIQCg"; // <GPGSID>
    public const string achievement_12 = "CgkI9Iy775wLEAIQCw"; // <GPGSID>
    public const string achievement_13 = "CgkI9Iy775wLEAIQDA"; // <GPGSID>
    public const string achievement_14 = "CgkI9Iy775wLEAIQDQ"; // <GPGSID>
    public const string achievement_15 = "CgkI9Iy775wLEAIQDg"; // <GPGSID>
    public const string achievement_16 = "CgkI9Iy775wLEAIQDw"; // <GPGSID>
    public const string achievement_17 = "CgkI9Iy775wLEAIQOQ"; // <GPGSID>
    public const string achievement_18 = "CgkI9Iy775wLEAIQEQ"; // <GPGSID>
    public const string achievement_19 = "CgkI9Iy775wLEAIQEg"; // <GPGSID>
    public const string achievement_20 = "CgkI9Iy775wLEAIQEw"; // <GPGSID>
    public const string achievement_21 = "CgkI9Iy775wLEAIQFA"; // <GPGSID>
    public const string achievement_22 = "CgkI9Iy775wLEAIQFQ"; // <GPGSID>
    public const string achievement_23 = "CgkI9Iy775wLEAIQFg"; // <GPGSID>
    public const string achievement_24 = "CgkI9Iy775wLEAIQFw"; // <GPGSID>
    public const string achievement_25 = "CgkI9Iy775wLEAIQGA"; // <GPGSID>
    public const string achievement_26 = "CgkI9Iy775wLEAIQGQ"; // <GPGSID>
    public const string achievement_27 = "CgkI9Iy775wLEAIQGg"; // <GPGSID>
    public const string achievement_28 = "CgkI9Iy775wLEAIQGw"; // <GPGSID>
    public const string achievement_29 = "CgkI9Iy775wLEAIQHA"; // <GPGSID>
    public const string achievement_30 = "CgkI9Iy775wLEAIQHQ"; // <GPGSID>
    public const string achievement_31 = "CgkI9Iy775wLEAIQHg"; // <GPGSID>
    public const string achievement_32 = "CgkI9Iy775wLEAIQHw"; // <GPGSID>
    public const string achievement_33 = "CgkI9Iy775wLEAIQIA"; // <GPGSID>
    public const string achievement_34 = "CgkI9Iy775wLEAIQIQ"; // <GPGSID>
    public const string achievement_35 = "CgkI9Iy775wLEAIQIg"; // <GPGSID>
    public const string achievement_36 = "CgkI9Iy775wLEAIQNQ"; // <GPGSID>
    public const string achievement_37 = "CgkI9Iy775wLEAIQIw"; // <GPGSID>
    public const string achievement_38 = "CgkI9Iy775wLEAIQJA"; // <GPGSID>
    public const string achievement_39 = "CgkI9Iy775wLEAIQJQ"; // <GPGSID>
    public const string achievement_40 = "CgkI9Iy775wLEAIQJg"; // <GPGSID>
    public const string achievement_41 = "CgkI9Iy775wLEAIQJw"; // <GPGSID>
    public const string achievement_42 = "CgkI9Iy775wLEAIQKA"; // <GPGSID>
    public const string achievement_43 = "CgkI9Iy775wLEAIQLg"; // <GPGSID>
    public const string achievement_44 = "CgkI9Iy775wLEAIQKQ"; // <GPGSID>
    public const string achievement_45 = "CgkI9Iy775wLEAIQKg"; // <GPGSID>
    public const string achievement_46 = "CgkI9Iy775wLEAIQKw"; // <GPGSID>
    public const string achievement_47 = "CgkI9Iy775wLEAIQLA"; // <GPGSID>
    public const string achievement_48 = "CgkI9Iy775wLEAIQLQ"; // <GPGSID>
    public const string achievement_49 = "CgkI9Iy775wLEAIQMw"; // <GPGSID>
    public const string achievement_50 = "CgkI9Iy775wLEAIQNA"; // <GPGSID>
    public const string achievement_51 = "CgkI9Iy775wLEAIQEA"; // <GPGSID>

    public const string leaderboard = "CgkI9Iy775wLEAIQOg"; // <GPGSID>
    public const string leaderboard_2 = "CgkI9Iy775wLEAIQOw"; // <GPGSID>
    public const string leaderboard_3 = "CgkI9Iy775wLEAIQPA"; // <GPGSID>
    public const string leaderboard_4 = "CgkI9Iy775wLEAIQPQ"; // <GPGSID>
    public const string leaderboard_5 = "CgkI9Iy775wLEAIQPg"; // <GPGSID>
    public const string leaderboard_6 = "CgkI9Iy775wLEAIQPw"; // <GPGSID>
    public const string leaderboard_7 = "CgkI9Iy775wLEAIQQA"; // <GPGSID>
    public const string leaderboard_8 = "CgkI9Iy775wLEAIQQQ"; // <GPGSID>
    public const string leaderboard_9 = "CgkI9Iy775wLEAIQQg"; // <GPGSID>
    public const string leaderboard_10 = "CgkI9Iy775wLEAIQQw"; // <GPGSID>
    public const string leaderboard_11 = "CgkI9Iy775wLEAIQRA"; // <GPGSID>
    public const string leaderboard_12 = "CgkI9Iy775wLEAIQRQ"; // <GPGSID>
    public const string leaderboard_13 = "CgkI9Iy775wLEAIQRg"; // <GPGSID>
    public const string leaderboard_14 = "CgkI9Iy775wLEAIQTA"; // <GPGSID>
}

