// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_importance_of_moderation = "CgkI9Iy775wLEAIQLA"; // <GPGSID>
        public const string leaderboard_mix_mode__light__44 = "CgkI9Iy775wLEAIQQA"; // <GPGSID>
        public const string achievement_no_problem = "CgkI9Iy775wLEAIQBA"; // <GPGSID>
        public const string achievement_welcome_to_find_or_set = "CgkI9Iy775wLEAIQEA"; // <GPGSID>
        public const string achievement_long_battle = "CgkI9Iy775wLEAIQJA"; // <GPGSID>
        public const string achievement_what_the_light = "CgkI9Iy775wLEAIQGw"; // <GPGSID>
        public const string achievement_detective_of_the_find = "CgkI9Iy775wLEAIQOQ"; // <GPGSID>
        public const string achievement_allrounder = "CgkI9Iy775wLEAIQLQ"; // <GPGSID>
        public const string achievement_between_the_light_and_darkness = "CgkI9Iy775wLEAIQDg"; // <GPGSID>
        public const string achievement_with_my_friend = "CgkI9Iy775wLEAIQNQ"; // <GPGSID>
        public const string achievement_disaster = "CgkI9Iy775wLEAIQKQ"; // <GPGSID>
        public const string achievement_a_piece_of_find = "CgkI9Iy775wLEAIQEg"; // <GPGSID>
        public const string achievement_convenient_to_find_find = "CgkI9Iy775wLEAIQEQ"; // <GPGSID>
        public const string achievement_4415 = "CgkI9Iy775wLEAIQDw"; // <GPGSID>
        public const string achievement_seethrough = "CgkI9Iy775wLEAIQGA"; // <GPGSID>
        public const string achievement_i_dont_like_that_either = "CgkI9Iy775wLEAIQJw"; // <GPGSID>
        public const string achievement_finding_genius = "CgkI9Iy775wLEAIQGg"; // <GPGSID>
        public const string achievement_thank_you_for_watching_this_show = "CgkI9Iy775wLEAIQKw"; // <GPGSID>
        public const string achievement_i_dont_need_your_help = "CgkI9Iy775wLEAIQBQ"; // <GPGSID>
        public const string achievement_nocturnal_animals = "CgkI9Iy775wLEAIQDA"; // <GPGSID>
        public const string leaderboard_challenge__simple_is_best = "CgkI9Iy775wLEAIQQg"; // <GPGSID>
        public const string achievement_that_was_close = "CgkI9Iy775wLEAIQBg"; // <GPGSID>
        public const string achievement_pressed_for_time = "CgkI9Iy775wLEAIQJg"; // <GPGSID>
        public const string achievement_find_or_set_or_picture_puzzle = "CgkI9Iy775wLEAIQKA"; // <GPGSID>
        public const string achievement_it_is_the_hardest_game_ever = "CgkI9Iy775wLEAIQAQ"; // <GPGSID>
        public const string achievement_what_was_that_card = "CgkI9Iy775wLEAIQBw"; // <GPGSID>
        public const string achievement_versatile_talents = "CgkI9Iy775wLEAIQIA"; // <GPGSID>
        public const string leaderboard_challenge__on_the_stage = "CgkI9Iy775wLEAIQRQ"; // <GPGSID>
        public const string achievement_upside_down = "CgkI9Iy775wLEAIQLg"; // <GPGSID>
        public const string achievement_i_cant_find_find = "CgkI9Iy775wLEAIQNA"; // <GPGSID>
        public const string achievement_for_this_achievement = "CgkI9Iy775wLEAIQIQ"; // <GPGSID>
        public const string achievement_light_is_important = "CgkI9Iy775wLEAIQCw"; // <GPGSID>
        public const string achievement_hide_and_hide = "CgkI9Iy775wLEAIQEw"; // <GPGSID>
        public const string leaderboard_light_mode = "CgkI9Iy775wLEAIQPA"; // <GPGSID>
        public const string leaderboard_challenge__the_switch = "CgkI9Iy775wLEAIQRA"; // <GPGSID>
        public const string leaderboard_hide_mode = "CgkI9Iy775wLEAIQOw"; // <GPGSID>
        public const string achievement_onesided_victory = "CgkI9Iy775wLEAIQJQ"; // <GPGSID>
        public const string achievement_brainstormer = "CgkI9Iy775wLEAIQCA"; // <GPGSID>
        public const string achievement_evening_person = "CgkI9Iy775wLEAIQHA"; // <GPGSID>
        public const string achievement_the_magician_of_darkness = "CgkI9Iy775wLEAIQFg"; // <GPGSID>
        public const string leaderboard_44_mode = "CgkI9Iy775wLEAIQPQ"; // <GPGSID>
        public const string achievement_its_on_my_brain = "CgkI9Iy775wLEAIQCg"; // <GPGSID>
        public const string achievement_overloaded = "CgkI9Iy775wLEAIQHg"; // <GPGSID>
        public const string achievement_instant_memoryer = "CgkI9Iy775wLEAIQFA"; // <GPGSID>
        public const string leaderboard_challenge__all_round = "CgkI9Iy775wLEAIQTA"; // <GPGSID>
        public const string achievement_leave_that_switch = "CgkI9Iy775wLEAIQKg"; // <GPGSID>
        public const string achievement_i_cant_see_it_but_its_okay = "CgkI9Iy775wLEAIQCQ"; // <GPGSID>
        public const string leaderboard_mix_mode__hide__light = "CgkI9Iy775wLEAIQPg"; // <GPGSID>
        public const string achievement_yeah_i_did_it = "CgkI9Iy775wLEAIQAg"; // <GPGSID>
        public const string achievement_0__0 = "CgkI9Iy775wLEAIQIw"; // <GPGSID>
        public const string leaderboard_challenge__i_want_more = "CgkI9Iy775wLEAIQRg"; // <GPGSID>
        public const string achievement_speed_racer = "CgkI9Iy775wLEAIQAw"; // <GPGSID>
        public const string leaderboard_challenge__memory_game = "CgkI9Iy775wLEAIQQw"; // <GPGSID>
        public const string leaderboard_mix_mode__hide__44 = "CgkI9Iy775wLEAIQPw"; // <GPGSID>
        public const string achievement_through_adversity_and_trials = "CgkI9Iy775wLEAIQFQ"; // <GPGSID>
        public const string achievement_is_there_any_find_of_that_card = "CgkI9Iy775wLEAIQFw"; // <GPGSID>
        public const string leaderboard_normal_mode = "CgkI9Iy775wLEAIQOg"; // <GPGSID>
        public const string achievement_real_speed_racer = "CgkI9Iy775wLEAIQMg"; // <GPGSID>
        public const string achievement_people_in_a_dark = "CgkI9Iy775wLEAIQDQ"; // <GPGSID>
        public const string achievement_need_more_concentrate = "CgkI9Iy775wLEAIQGQ"; // <GPGSID>
        public const string achievement_going_to_get_hypnosis = "CgkI9Iy775wLEAIQHQ"; // <GPGSID>
        public const string leaderboard_mix_mode__all = "CgkI9Iy775wLEAIQQQ"; // <GPGSID>
        public const string achievement_i_dont_know_whats_your_saying = "CgkI9Iy775wLEAIQMw"; // <GPGSID>
        public const string achievement_divine_position = "CgkI9Iy775wLEAIQIg"; // <GPGSID>
        public const string achievement_crazy_play = "CgkI9Iy775wLEAIQHw"; // <GPGSID>

}

